#!/bin/sh
AUR_REPO_DIR="$(cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)"
AUR_REPO="aur-fresh-builds"
cd "$AUR_REPO_DIR"
echo "[UPDATE] Creating $AUR_REPO DB"

# Delete old files
rm -f "$AUR_REPO_DIR"/*.db "$AUR_REPO_DIR"/*.files "$AUR_REPO_DIR"/*.sig "$AUR_REPO_DIR"/*.tar.gz &> /dev/null

# Sign all packages
#for FILE in $(ls "$AUR_REPO_DIR"/*.pkg.tar.zst); do
#	gpg --use-agent --output "$FILE.sig" --detach-sig "$FILE"
#done

# Create repo and add packages (everything is signed)
#repo-add --verify --sign "$AUR_REPO_DIR/$AUR_REPO.db.tar.gz" "$AUR_REPO_DIR"/*.pkg.tar.zst
repo-add --verify "$AUR_REPO_DIR/$AUR_REPO.db.tar.gz" "$AUR_REPO_DIR"/*.pkg.tar.zst

# Delete/rename files for pacman
mv "$AUR_REPO_DIR/$AUR_REPO.db.tar.gz" "$AUR_REPO_DIR/$AUR_REPO.db"
mv "$AUR_REPO_DIR/$AUR_REPO.files.tar.gz" "$AUR_REPO_DIR/$AUR_REPO.files"
ln -sfr "$AUR_REPO_DIR/$AUR_REPO.db" "$AUR_REPO_DIR/$AUR_REPO.db.tar.gz"
ln -sfr "$AUR_REPO_DIR/$AUR_REPO.files" "$AUR_REPO_DIR/$AUR_REPO.files.tar.gz"


#rm $AUR_REPO.db $AUR_REPO.files &> /dev/null

#mv $AUR_REPO.db.tar.gz $AUR_REPO.db &> /dev/null
#mv $AUR_REPO.files.tar.gz $AUR_REPO.files &> /dev/null

#ln -sfr $AUR_REPO_DIR/$AUR_REPO.db $AUR_REPO_DIR/$AUR_REPO.db.tar.gz
#ln -sfr $AUR_REPO_DIR/$AUR_REPO.files $AUR_REPO_DIR/$AUR_REPO.files.tar.gz

#mv $AUR_REPO.db.tar.gz.sig $AUR_REPO.db.sig &> /dev/null
#mv $AUR_REPO.files.tar.gz.sig $AUR_REPO.files.sig &> /dev/null
